### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by 58773622** [bkerler/android_universal#4]
pc@PC:~/android_universal$ ./makeramdisk.sh -filename boot.img
Traceback (most recent call last):
  File "root/scripts/makeramdisk.py", line 20, in <module>
    from bootsignature import sign, verify
  File "/home/pc/android_universal/root/scripts/bootsignature.py", line 18, in <module>
    from pyasn1_modules import rfc2459, rfc4055
ImportError: cannot import name 'rfc4055' from 'pyasn1_modules' (/usr/lib/python3/dist-packages/pyasn1_modules/__init__.py)

**Comment by bkerler** [comment]
Make sure you have the requirements installed. You need to install pyasn1-modules (https://github.com/etingof/pyasn1-modules)

**Comment by 58773622** [comment]
> 确保您已安装要求。您需要安装 pyasn1-modules ( https://github.com/etingof/pyasn1-modules )

I threw an error after installation！

root@PC:/home/pc/android_universal# ./makeramdisk.sh -filename boot.img

Makeramdisk Android v3.30 (c) B. Kerler 2019-2021
---------------------------------------------

Linux/Mac detected.
32Bit detected
Target: Boot
Unpacking image : boot.img to tmp
- Unpacking initramfs to tmp/ramdisk
Traceback (most recent call last):
  File "root/scripts/makeramdisk.py", line 850, in <module>
    main()
  File "root/scripts/makeramdisk.py", line 846, in main
    rdm.go(args, BOOTPATH, param)
  File "root/scripts/makeramdisk.py", line 676, in go
    self.unpack_initfs("rd.gz", self.RAMDISK)
  File "root/scripts/makeramdisk.py", line 265, in unpack_initfs
    rdcpio = self.guz(os.path.join(self.RPATH, filename))
  File "root/scripts/makeramdisk.py", line 248, in guz
    with gzip.open(filename, 'rb') as f:
  File "/usr/lib/python3.8/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/lib/python3.8/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/rd.gz'
root@PC:/home/pc/android_universal#

**Comment by 58773622** [comment]
root@DESKTOP-NM8UG5T:/home/pc/adbroot# ./makeramdisk.sh -filename boot.img

Makeramdisk Android v3.30 (c) B. Kerler 2019-2021
---------------------------------------------

Linux/Mac detected.
32Bit detected
Target: Boot
Unpacking image : boot.img to tmp
- Unpacking initramfs to tmp/ramdisk
Traceback (most recent call last):
  File "root/scripts/makeramdisk.py", line 850, in <module>
    main()
  File "root/scripts/makeramdisk.py", line 846, in main
    rdm.go(args, BOOTPATH, param)
  File "root/scripts/makeramdisk.py", line 676, in go
    self.unpack_initfs("rd.gz", self.RAMDISK)
  File "root/scripts/makeramdisk.py", line 268, in unpack_initfs
    p.stdin.write(rdcpio)
BrokenPipeError: [Errno 32] Broken pipe
root@DESKTOP-NM8UG5T:/home/pc/adbroot#
