### ISSUE TITLE
Could not use this tool

### ISSUE THREAD

**Issue by kayshinonome** [bkerler/android_universal#5]
```
kayshinonome@latitude-e6430 ~/Code/android_universal $ ./makeramdisk.sh -filename boot.img

Makeramdisk Android v3.30 (c) B. Kerler 2019-2021
---------------------------------------------

Linux/Mac detected.
32Bit detected
Target: Boot
AVBv2 signature detected.
VBMeta-Image-Hash: 			b6e4870834085deeee714c7161e2d8beb59c1f8ea5e9000ac2f50b1612d11139

Signature-RSA-Modulus (n):	d0f36f65633ad7100159d005df9978de23120cd3bb9ea6941c803527e72416681f45d4806f55c49e95d7e05840bb455224ef77804ef540c7e50325982b832f2081a594864c8e58878306fa95ef86528177fd140cfcb604a0a06242c932269c219bc7a551aa21410654e0554f2de00ff148f39e5698738f57d918fa56e6ec970f6b3b1486b6cd528bd7217924e084ee7d7960ddc30f7dfd28c8140521b405d526ecc2ebfb7def0993bd02e6028d18e0664391261fd68dc631b13b56edc5b579a1315430edec7e0bfe577507a1d71cf7b66047be094da7df0d5fac13b0663870ef83f3938a5ff612745176f085a76af0db4ba01eda353fddcfdfa48fd4f50d662314acbf72511ea4f8bcda64855e8595d1c56e970c4a63504a237d0c123665c25a18ab2e5b22f79742e3566cfaf4dd1d9ee6e5f92e98c482357009a7ee9106f49158333a7f6596c5f6e230665989f8d66e31634156d9b2133e6bee81b7fef673b61846a5588062688a2269e94b4f1a2790ee39c0f6a1a158ea172823d82b665c09a5f4e2c76d349c4bb36d178e4ad0a7612957b63ab01b64e4a99acd5e95f188d6540625cf9d607b31006acb2969b80b5b2d4f4a15c9e6f71b421028e322b3ad3165cb16a485c2cfe8a0f41b66948aa74d1c4475fbb4b9b6879bfa51a1cfa38932e88063f9d2d1ab4a7841d907addaf0d83bc78ae8e98ef645dac0a0db5685b3f9
Signature-n0inv: 			2995684981
Unpacking image : boot.img to tmp
- Unpacking initramfs to tmp/ramdisk
Traceback (most recent call last):
  File "/home/kayshinonome/Code/android_universal/root/scripts/makeramdisk.py", line 850, in <module>
    main()
  File "/home/kayshinonome/Code/android_universal/root/scripts/makeramdisk.py", line 846, in main
    rdm.go(args, BOOTPATH, param)
  File "/home/kayshinonome/Code/android_universal/root/scripts/makeramdisk.py", line 676, in go
    self.unpack_initfs("rd.gz", self.RAMDISK)
  File "/home/kayshinonome/Code/android_universal/root/scripts/makeramdisk.py", line 265, in unpack_initfs
    rdcpio = self.guz(os.path.join(self.RPATH, filename))
  File "/home/kayshinonome/Code/android_universal/root/scripts/makeramdisk.py", line 248, in guz
    with gzip.open(filename, 'rb') as f:
  File "/usr/lib/python3.9/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/lib/python3.9/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/rd.gz'
```
My boot.img [boot.zip](https://github.com/bkerler/android_universal/files/7187203/boot.zip)
My vbmeta.img [vbmeta.zip](https://github.com/bkerler/android_universal/files/7187212/vbmeta.zip)

**Comment by kayshinonome** [comment]
In case you needed to know, this device runs android 9

**Comment by bkerler** [comment]
Boot doesn't have any ramdisk on android >=9, thus you need to use recovery or patch init and add your custom ramdisk manually as for now

**Comment by kayshinonome** [comment]
Ah, thank you

**Comment by ChillVibesMushroom** [comment]
Is there a tutorial for this that doesn't waste my time I'm at work rn
